### ISSUE TITLE
Labels for plot_correlation

### ISSUE THREAD

**Issue by rbratslaver** [boxuancui/DataExplorer#138]
Hi - thanks for this awesome package. I was wondering if there's a way to display the actual correlation coefficient values in the plot generated by plot_correlation. 

Thanks for your time.

**Comment by boxuancui** [comment]
I believe if the number of columns is less than 20, it will be displayed: https://github.com/boxuancui/DataExplorer/blob/master/R/plot_correlation.r#L65-L69. Otherwise, the texts will be cluttered together making it unreadable.

With the said, you can always re-use the code and overwrite `plot_correlation` as needed.
