### ISSUE TITLE
R version compatibility

### ISSUE THREAD

**Issue by caduguimaraes** [boxuancui/DataExplorer#150]
Hi All.

No R version 1.3.1093 (newest at the moment) compatibility at all? 

Thanks in advance

**Comment by boxuancui** [comment]
I am not sure if I am following, but the latest R version should be 4.0.3 according to [CRAN](https://cloud.r-project.org/). Submitted R packages should never have compatibility issues. However, DataExplorer is archived due to some unfixed bugs, and I am working on a fix (see #148 ). You can still install from GitHub though.

**Comment by caduguimaraes** [comment]
Sorry, iI mean, R Studio. 

Just for info, I had the follow error message below:
Warning in install.packages :
  package ‘DataExplorer’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

Thank you

**Comment by boxuancui** [comment]
Please refer to #148 . You can also install from GitHub for now.
