### ISSUE TITLE
Add support for non-ASCII characters

### ISSUE THREAD

**Issue by boxuancui** [boxuancui/DataExplorer#19]
Reported by @djhurio in #16 

> I have installed development version. I am not getting errors any more. Report is generated with a warning:
> 
> ```
> Warning message:
> In writeLines(if (encoding == "") res else native_encode(res, to = encoding),  :
>   invalid char string in output conversion`
> ```
> 
> And report is unreadable.

**Comment by boxuancui** [comment]
@djhurio Do you still have this problem with the latest version? I tested data with a different language and it works fine for me.

**Comment by djhurio** [comment]
Hi @boxuancui!

It works for me now. And probably the problem was on my side. I had a command `options(encoding = "UTF-8")` in my code before. In this case there is problem with unicode characters and report is not generated properly in test cases. After changing the option to `options(encoding = "")` the problem is gone and report is generated correctly in all test cases. It seems I have to be careful with the `options(encoding = "UTF-8")`.

The only error I am getting is this, but as I told report is generated correctly:

    Output created: T:/ .... /TMS2015_sample_data_2.html
    Error in !args[["quiet"]] : invalid argument type

Thanks!

**Comment by boxuancui** [comment]
That error is fixed in #34 . Please install the latest develop branch if you wish. Thanks for using DataExplorer!
