### ISSUE TITLE
install rprojroot as part of install process?

### ISSUE THREAD

**Issue by nmalizia** [boxuancui/DataExplorer#35]
Hey sir! Wondering if it's possible to set it up so the library installs rprojroot as part of the install process. I didn't have it installed and as such it popped an error for me.

**Comment by boxuancui** [comment]
Do you remember when it happened? When installing the package or when loading the package, or when you call specific functions?

**Comment by nmalizia** [comment]
Great question - I believe it was at initial import, not 100% sure though.

**Comment by boxuancui** [comment]
I need to reproduce the error, so could you do the following?

1. Remove **rprojroot** and **DataExplorer** package if you have already installed it.
1. Type `R.version` and `sessionInfo()` and paste the output here. 
1. Install **DataExplorer** package again, and paste the exact error message here.

This should not happen, because **rprojroot** is listed as one of the imports in **rmarkdown**, according to the DESCRIPTION file (line 3 item 11): https://cran.r-project.org/web/packages/rmarkdown/index.html.

If you are using Rstudio for package installation, could you also make sure you have checked the Install dependencies box?
![rstudio](https://cloud.githubusercontent.com/assets/3045138/21021869/6f510efc-bd48-11e6-9d25-4c67427c016e.png)

If you are doing from console, could you make sure it is something like this?

    install.packages("DataExplorer", dependencies = TRUE)

**Comment by boxuancui** [comment]
After some thoughts, let me guess what happened. You installed either **rmarkdown** or **sparklyr**  at first, then removed **rprojroot** manually afterwards. Is this true?

If it is, I don't think this is something a package could control. You have to either re-install the reverse dependencies (revere imports) with `dependencies = TRUE` or install the missing dependency (**rprojroot** in this case) manually.

Let me know.

**Comment by boxuancui** [comment]
I have added **rprojroot** to Suggests, so it should automatically install it without error. We will see when it is released to CRAN. Please re-open if this doesn't fix it.

**Comment by nmalizia** [comment]
OK, sorry for my radio silence. I was working off a fresh install of 3.
something. I'll try to install it on another EC2 and see if it creates an
error. Thanks man - this library is cool!

**Comment by boxuancui** [comment]
You might want to do `devtools::install_github("boxuancui/DataExplorer", ref = "develop")` since it is only available in the develop branch.

**Comment by boxuancui** [comment]
I recall my previous previous comment. Putting it in Suggests does not fix it. However, I believe I find the true cause. In my DESCRIPTION file, it was importing rmarkdown 0.9.5, but rprojroot package was added to the NAMESPACE after that version. So, I changed 0.9.5 to current version, and it should fix that problem, for real this time.

**Comment by nmalizia** [comment]
Thanks dude!
