### ISSUE TITLE
Add option for title on plots

### ISSUE THREAD

**Issue by rlshuhart** [boxuancui/DataExplorer#45]
Thanks for the library!

Would it be possible to add an option for a title to the plots?

I think all it would require is 
function(data, **title=NULL**) {
     [ggplot code] +
     ggtitle(title)

Ryan

**Comment by boxuancui** [comment]
Hi, there are two types of titles for multiple plots:
1. A single title on top of all plots
1. Individual title for each plot

The package uses [gridExtra](https://cran.r-project.org/package=gridExtra) to manage layout, so adding titles could be more than just `ggtitle(...)`. On the other hand, if you would like to add a title for each plot, `ggtitle(...)` needs to handle each plot dynamically, instead of a fixed string.

Which one is your use case?

**Comment by rlshuhart** [comment]
I personally would have more of the use case for a single title on top of a plot or grid of plots.

Thanks!
