### ISSUE TITLE
Return plots as ggplot objects

### ISSUE THREAD

**Issue by AndreaPi** [boxuancui/DataExplorer#78]
Are the DataExplorer plots `ggplot` objects? I would like to use `patchwork` to patch together two `plot_missing` plots for two different datasets (actually, the same data set, but split by a binary variable). If the plot generated by `plot_missing` is a `ggplot` object, then returning it would allow me to patch two (or more) of them together using `patchwork`.

PS excellent package, thanks for putting it on CRAN!

**Comment by boxuancui** [comment]
Yes it is a `ggplot` object. However, the function is already returning something.

Two options IMO:
1. Wrap the `ggplot` object in a list and return along with other things.
1. The missing value profile is already [returned](https://github.com/boxuancui/DataExplorer/blob/master/R/plot_missing.r#L70) and it goes directly into the plot function from [line 57 - 66](https://github.com/boxuancui/DataExplorer/blob/master/R/plot_missing.r#L57-L66). You can always create your own `ggplot` object by reusing/modifying the code.

I am more inclined to option 2, since you already get what you need from the returned object, and it is cleaner. Option 1 seems a little redundant, and **might** conflict with future development of this package. Again, I do not have clear vision about what that is, but would like to keep it clean and simple for now.

Open for suggestions.

And, thanks for using DataExplorer!

**Comment by AndreaPi** [comment]
Thanks for the explanation! So, if I understand correctly, `plot_missing` **already** creates a `ggplot` object (called `output` in your code). However, it doesn't return it, because it already returns (invisibly) `missing_value`,  the dataframe containing the missing value profile.
Option 2 would work, but I don't like it because it's basically duplicating work: you suggest that I assign  `missing_value` to a variable, e.g.

```
missing_value_profile <- plot_missing(my_dataframe)
```
and then create a plot copying the `ggplot` code in `plot_missing`. But you already create **and** plot `output` in your code, so I'd generate the plot twice. 

Instead, I  suggest adding an optional parameter defaulting to `FALSE`:

```
plot_missing <- function(data, title = NULL, ggtheme = theme_gray(), theme_config = list("legend.position" = c("bottom")), return_plot_object = FALSE)
 ```

and a simple `if` at the end of `plot_missing`:

```
  ## Set return object
 if (return_plot_object)
  return(invisible(list(output, missing_value)))
 else 
  return(invisible(missing_value))
}
```

**Comment by boxuancui** [comment]
It will be released in v0.7. Please use either workarounds in the mean time.

**Comment by AndreaPi** [comment]
Absolutely! Thanks a lot :-D  BTW, another possible solution:

-  expose a function which creates the missing value profile, e.g., `missing_values_profile()`
-  have `plot_missing()` call it
- at this point, `plot_missing()` can simply always return the `ggplot` object (`output`). If the user wants to get the dataframe containing the missing value profile, instead, s/he can directly call `missing_values_profile()`.

This way, `plot_missing()` would always return the same object, no matter what its inputs are: I don't think this is something indispensable, but maybe it could simplify your life as a mantainer. At the same time, you would still maintain only one function to generate the missing value profile (`missing_values_profile()`), because `plot_missing()` would internally call `missing_values_profile()`. 

Personally I think that the first solution (adding the optional argument `return_plot_object` to `plot_missing()`) should be fine, and it wouldn't break old code, but of course the decision is yours. Thanks again!!

**Comment by boxuancui** [comment]
Added `profile_missing()`, and `plot_missing()` calls that directly.
All `plot_*` functions return the ggplot objects now.
